@startuml

!pragma layout smetana

class Member

class BoardMember

class Event{
assign(l : Location) : void
}

class Conference

class BoardMeeting

class Location

class Person

class AAUOC{
newLocation(l : Location) : void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

Location - Event

AAUOC o-- Location
AAUOC o-- Event
AAUOC o-- Person

BoardMeeting - BoardMember

Event - Member

@enduml