@startuml

!pragma layout smetana

class Member

class BoardMember

class Event

class Conference

class BoardMeeting

class Location

class Person

class AAUOC

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

Location - Event

AAUOC o-- Location
AAUOC o-- Event
AAUOC o-- Person

BoardMeeting - BoardMember

Event - Member

@enduml